#!/bin/bash

# System update
echo 'Updating your system...'
sudo pacman -Syyu --noconfirm

# Create the clone directory if it doesn't exist
mkdir -p ~/clone

gitt clone https://github.com/rashadalsharpini/linux-stuff ~/clone/linux-stuff
git clone https://github.com/rashadalsharpini/nvim ~/.config/nvim
# Copy and overwrite configuration files
cp -rf ~/clone/linux-stuff/fish ~/.config/
cp -rf ~/clone/linux-stuff/kitty ~/.config/
cp -rf ~/clone/linux-stuff/bin ~/.local/
cp -rf ~/clone/linux-stuff/lf ~/.config/
cp -f ~/clone/linux-stuff/zsh/.zshrc ~/
cp -rf ~/clone/linux-stuff/mpv ~/.config/


# Clone repositories into specific directories

# Install required packages without confirmation
sudo pacman -S --noconfirm btop lsd lf mpv kitty neovim fish yt-dlp zsh \
betterlockscreen xclip xfce4-clipman-plugin zathura zathura-pdf-poppler progress obsidian zsh-autosuggestions zsh-syntax-highlighting \
power-profiles-daemon zen-browser-bin discord telegram-desktop nvidia nvidia-utils nvidia-settings nvidia-prime wine lutris qbittorrent nautilus
# Change default shell to fish non-interactively
chsh -s /usr/bin/zsh

